// angular-blazor/angular-app-with-blazor/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div class="content">
      <h1>Welcome to {{title}}</h1>
      <p>This is an Angular application that can render a Blazor components.</p>
      <p>
        <button (click)="addBlazorCounter()">Add Blazor component</button>
        <button (click)="removeBlazorCounter()">Remove Blazor component</button>
      </p>

      <div *ngFor="let counter of blazorCounters">
        <comment-antd>
        </comment-antd>
      </div>
    </div>
  `,
  styles: []
})
export class AppComponent {
  title = 'Hackfest 2022';

  blazorCounters: any[] = [];
  nextCounterIndex = 1;

  addBlazorCounter() {
    const index = this.nextCounterIndex++;
    this.blazorCounters.push({
      title: `Counter ${index}`,
      incrementAmount: index,
    });
  }

  removeBlazorCounter() {
    this.blazorCounters.pop();
  }
}

// react-blazor/react-blazor/src/App.js
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [nextCounterIndex, setNextCounterIndex] = useState(1);
  const [blazorCounters, setBlazorCounters] = useState([]);
  const addBlazorCounter = () => {
    const index = nextCounterIndex;
    setNextCounterIndex(index + 1);
    setBlazorCounters(blazorCounters.concat([{
      title: `Counter ${index}`,
      incrementAmount: index,
    }]));
  };
  const removeBlazorCounter = () => {
    setBlazorCounters(blazorCounters.slice(0, -1));
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          <button onClick={addBlazorCounter}>Add Blazor counter</button> &nbsp;
          <button onClick={removeBlazorCounter}>Remove Blazor counter</button>
        </p>

        {blazorCounters.map(counter =>
          <div key={counter.title}>
            <nic-component></nic-component>
          </div>
        )}

      </header>
    </div>
  );
}

export default App;
